# Generated by Django 4.2 on 2024-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=1000, unique=True)),
                ('short_url', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
