# Generated by Django 4.2 on 2024-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['original_url'], name='url_shortne_origina_da7ac2_idx'),
        ),
    ]
